<?php
      $this->db->query("DROP TABLE IF EXISTS w_activitessappr CASCADE");
      $this->db->query("CREATE TABLE w_activitessappr AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM activitessappr_vue') AS t(idact Integer, designationact varchar, idtypact Integer, designationtypact varchar, idtyptrav Integer, designationtyptrav varchar, idprogproj Integer, progproj varchar, montanttotalact Integer, dureeact real, datreceptprovact Date, observationact varchar, idbail Integer, bailleur varchar, idpart Integer, partmiseoeuvre varchar)");
            
      $this->db->query("DROP TABLE IF EXISTS w_bailfondptf CASCADE");
      $this->db->query("CREATE TABLE w_bailfondptf AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM bailfondptf_vue') AS t(idptf Integer, idtypact Integer, iddom Integer, representantptf varchar, gdbailfondptf varchar, bailfondptf varchar, agexecptf varchar, progprojptf varchar, autresptf varchar, firmeptf varchar, designationptf varchar, adresseptf varchar, mailptf varchar, telephoneptf varchar, faxptf varchar, sitewebptf varchar, bpptf varchar, persressptf varchar, mailprptf varchar, telprptf varchar, zoneptf varchar, budgettotalptf Integer, validation varchar)");
            
      $this->db->query("DROP TABLE IF EXISTS w_dechsolid_vue CASCADE");
      $this->db->query("CREATE TABLE w_dechsolid_vue AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM dechsolid_vue') AS t(iddso Integer, nidso varchar, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, nbfokayantsceprecollgom Integer, nbmngaccesgom Integer, nbmngpratiqtraitindgom Integer, nomsitdec varchar, superficiesitdec real, voldecsitdec real, longsitdec real, latsitdec real, altsitdec Integer, idlocd Integer, desognationlocd varchar, idfokd Integer, designationfokd varchar, nomsittragom varchar, volomtraitesittragom real, uniteutilsittragom varchar, longsittragom real, latsittragom real, altsittragom Integer, formelsittragom varchar, mecaniquesittragom varchar, manuelsittragom varchar, idloct Integer, designationloct varchar, idfokt Integer, designationfokt varchar, idscegom Integer, designationscegom varchar, volordurecollscegom real, datecollinfoscegom Date, datecolldebscegom Date, valdreaugom varchar, datvaldreaugom Date, valcentralgom varchar, datvalcentralgom Date, valsiggom varchar, datvalsiggom Date, datecollgom Date, datecolldebgom Date, idactdso Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_dechsolidtot CASCADE");
      $this->db->query("CREATE TABLE w_dechsolidtot AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM dechsolidtot_vue') AS t(iddso Integer, nidso varchar, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, nbfokayantsceprecollgom Integer, nbmngaccesgom Integer, nbmngpratiqtraitindgom Integer, nomsitdec varchar, superficiesitdec real, voldecsitdec real, longsitdec real, latsitdec real, altsitdec Integer, idlocd Integer, desognationlocd varchar, idfokd Integer, designationfokd varchar, nomsittragom varchar, volomtraitesittragom real, uniteutilsittragom varchar, longsittragom real, latsittragom real, altsittragom Integer, formelsittragom varchar, mecaniquesittragom varchar, manuelsittragom varchar, idloct Integer, designationloct varchar, idfokt Integer, designationfokt varchar, idscegom Integer, designationscegom varchar, volordurecollscegom real, datecollinfoscegom Date, datecolldebscegom Date, valdreaugom varchar, datvaldreaugom Date, valcentralgom varchar, datvalcentralgom Date, valsiggom varchar, datvalsiggom Date, datecollgom Date, datecolldebgom Date, idactdso Integer, idact Integer, designationact varchar, idtypact Integer, designationtypact varchar, idtyptrav Integer, designationtyptrav varchar, idappr Integer, designationappr varchar, idprogproj Integer, progproj varchar, montanttotalact Integer, dureeact real, datreceptprovact Date, observationact varchar, idbail Integer, bailleur varchar, idpart Integer, partmiseoeuvre varchar)");
            
      $this->db->query("DROP TABLE IF EXISTS w_eauusee CASCADE");
      $this->db->query("CREATE TABLE w_eauusee AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM eauusee_vue') AS t(ideuep Integer, nieuep varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, nbbassintamponeuep Integer, volumetraiteeuep real, existsceeuep varchar, existsitetraiteuep varchar, idsceeuep Integer, nomsceeuep varchar, voleudevresoeuep real, voleudevnatureeuep real, voleuindustdevresoeuep real, voleuindustdevnatureeuep real, euindustctrleuep varchar, datecollsce Date, datecolldebsce Date, valdreaueuep Integer, datvaldreaueuep Date, valsigeuep Integer, datvalsigeuep Date, valcentraleuep Integer, datvalcentraleuep Date, datecolleuep Date, datecolldebeuep Date, idacteuep Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_eauuseetot CASCADE");
      $this->db->query("CREATE TABLE w_eauuseetot AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM eauuseetot_vue') AS t(ideuep Integer, nieuep varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, nbbassintamponeuep Integer, volumetraiteeuep real, existsceeuep varchar, existsitetraiteuep varchar, idsceeuep Integer, nomsceeuep varchar, voleudevresoeuep real, voleudevnatureeuep real, voleuindustdevresoeuep real, voleuindustdevnatureeuep real, euindustctrleuep varchar, datecollsce Date, datecolldebsce Date, valdreaueuep Integer, datvaldreaueuep Date, valsigeuep Integer, datvalsigeuep Date, valcentraleuep Integer, datvalcentraleuep Date, datecolleuep Date, datecolldebeuep Date, idacteuep Integer, idact Integer, designationact varchar, idtypact Integer, designationtypact varchar, idtyptrav Integer, designationtyptrav varchar, idappr Integer, designationappr varchar, idprogproj Integer, progproj varchar, montanttotalact Integer, dureeact real, datreceptprovact Date, observationact varchar, idbail Integer, bailleur varchar, idpart Integer, partmiseoeuvre varchar)");
            
      $this->db->query("DROP TABLE IF EXISTS w_fktsansinfraeau CASCADE");
      $this->db->query("CREATE TABLE w_fktsansinfraeau AS SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 'SELECT localites.idfok FROM infraeau INNER JOIN localites ON infraeau.idloc = localites.idloc GROUP BY localites.idfok') AS t(fkt Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_hygiene_vue CASCADE");
      $this->db->query("CREATE TABLE w_hygiene_vue AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM hygiene_vue') AS t(idhyg Integer, nihyg varchar, niveau varchar, idp Integer, province varchar, idr Integer, region varchar, idd Integer, district varchar, idc Integer, commune varchar, popurbcom Integer, poptotcom Integer, idf Integer, fokontany varchar, idl Integer, localites varchar, nbdlm Integer, valdreau varchar, datvaldreau Date, valsig varchar, datvalsig Date, valcentral varchar, datvalcentral Date, datecolldebhyg Date, datecollhyg Date, idacthyg Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_hygiene1 CASCADE");
      $this->db->query("CREATE TABLE w_hygiene1 AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM hygiene1_vue') AS t(id Integer, idhyg Integer, nihyg varchar, niveau varchar, idp Integer, province varchar, idr Integer, region varchar, idd Integer, district varchar, idc Integer, commune varchar, popurbcom Integer, poptotcom Integer, idf Integer, fokontany varchar, idl Integer, localites varchar, nbdlm Integer, valdreau varchar, datvaldreau Date, valsig varchar, datvalsig Date, valcentral varchar, datvalcentral Date, datecolldebhyg Date, datecollhyg Date, idacthyg Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_infraass CASCADE");
      $this->db->query("CREATE TABLE w_infraass AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM infraass_vue') AS t(idlatinf Integer, niia varchar, idtyplat Integer, designationtyplat varchar, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, idutil Integer, designationutil varchar, idmodgest Integer, designationmodgest varchar, nbbenelatinf Integer, accpershandilatinf varchar, latinstsepareelatinf varchar, nbcompatlatinf Integer, nbdlmlatinf Integer, nbdouchelatinf Integer, valdreaulatinf varchar, datvaldreaulatinf Date, valsiglatinf varchar, datvalsiglatinf Date, valcentrallatinf varchar, datvalcentrallatinf Date, observations varchar, idactlatinf Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_infraasstot CASCADE");
      $this->db->query("CREATE TABLE w_infraasstot AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM infraasstot_vue') AS t(idlatinf Integer, niia varchar, idtyplat Integer, designationtyplat varchar, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, idutil Integer, designationutil varchar, idmodgest Integer, designationmodgest varchar, nbbenelatinf Integer, accpershandilatinf varchar, latinstsepareelatinf varchar, nbcompatlatinf Integer, nbdlmlatinf Integer, nbdouchelatinf Integer, valdreaulatinf varchar, datvaldreaulatinf Date, valsiglatinf varchar, datvalsiglatinf Date, valcentrallatinf varchar, datvalcentrallatinf Date, observations varchar, idactlatinf Integer, idact Integer, designationact varchar, idtypact Integer, designationtypact varchar, idtyptrav Integer, designationtyptrav varchar, idappr Integer, designationappr varchar, idprogproj Integer, progproj varchar, montanttotalact Integer, dureeact real, datreceptprovact Date, observationact varchar, idbail Integer, bailleur varchar, idpart Integer, partmiseoeuvre varchar)");
            
      $this->db->query("DROP TABLE IF EXISTS w_infraeau CASCADE");
      $this->db->query("CREATE TABLE w_infraeau AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM infraeau_vue') AS t(idino Integer, nipo varchar, idtypineau Integer, designationtypineau varchar, idfoncouvr Integer, desigfoncouvr varchar, idmodgest Integer, designationmodgest varchar, nomgestino varchar, idutil Integer, designationutil varchar, idmil Integer, designationmil varchar, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, nbbeneino Integer, nbbfino Integer, nbbpino Integer, nbbsino Integer, nbbfnfoncino Integer, nbbpnfoncino Integer, nbbsnfoncino Integer, nbreservino Integer, longino real, latino real, altino Integer, valdreauino varchar, datvaldreauino Date, valsigino varchar, datvalsigino Date, valcentralino varchar, datvalcentralino Date, idactino Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_infraeautot CASCADE");
      $this->db->query("CREATE TABLE w_infraeautot AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM infraeautot_vue') AS t(idino Integer, nipo varchar, idtypineau Integer, designationtypineau varchar, idfoncouvr Integer, desigfoncouvr varchar, idmodgest Integer, designationmodgest varchar, nomgestino varchar, idutil Integer, designationutil varchar, idmil Integer, designationmil varchar, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, nbbeneino Integer, nbbfino Integer, nbbpino Integer, nbbsino Integer, nbbfnfoncino Integer, nbbpnfoncino Integer, nbbsnfoncino Integer, nbreservino Integer, longino real, latino real, altino Integer, valdreauino varchar, datvaldreauino Date, valsigino varchar, datvalsigino Date, valcentralino varchar, datvalcentralino Date, idactino Integer, idact Integer, designationact varchar, idtypact Integer, designationtypact varchar, idtyptrav Integer, designationtyptrav varchar, idprogproj Integer, progproj varchar, montanttotalact Integer, dureeact real, datreceptprovact Date, observationact varchar, idbail Integer, bailleur varchar, idpart Integer, partmiseoeuvre varchar)");
            
      $this->db->query("DROP TABLE IF EXISTS w_partmisoeuvre CASCADE");
      $this->db->query("CREATE TABLE w_partmisoeuvre AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM partmisoeuvre_vue') AS t(idptf Integer, idtypact Integer, iddom Integer, representantptf varchar, gdbailfondptf varchar, bailfondptf varchar, agexecptf varchar, progprojptf varchar, autresptf varchar, firmeptf varchar, designationptf varchar, adresseptf varchar, mailptf varchar, telephoneptf varchar, faxptf varchar, sitewebptf varchar, bpptf varchar, persressptf varchar, mailprptf varchar, telprptf varchar, zoneptf varchar, budgettotalptf Integer, validation varchar)");
            
                //$this->db->query("DROP TABLE IF EXISTS w_pointdeau CASCADE");
                //$this->db->query("CREATE TABLE w_pointdeau AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM pointdeau_vue') AS t(idpdo Integer, idtyppdo Integer, designation2typpdo varchar, idutil Integer, designationutil varchar, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, idmodgest Integer, designationmodgest varchar, idfoncouvr Integer, desigfoncouvr varchar, idino Integer, numpdo Integer, gerantpdo varchar, nbbenepdo Integer, longpdo real, latpdo real, altpdo Integer, idtypineau Integer, designationtypineau varchar, nbpdo Integer, idmil Integer, designationmil varchar, valdreauino varchar, datvaldreauino Date, valsigino varchar, datvalsigino Date, valcentralino varchar, datvalcentralino Date)");
            
                //$this->db->query("DROP TABLE IF EXISTS w_pointdeau1 CASCADE");
                //$this->db->query("CREATE TABLE w_pointdeau1 AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM pointdeau1_vue') AS t(id Integer, idpdo Integer, idtyppdo Integer, designation2typpdo varchar, idutil Integer, designationutil varchar, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, idmodgest Integer, designationmodgest varchar, idfoncouvr Integer, desigfoncouvr varchar, idino Integer, numpdo Integer, gerantpdo varchar, nbbenepdo Integer, longpdo real, latpdo real, altpdo Integer, idtypineau Integer, designationtypineau varchar, nbpdo Integer, idmil Integer, designationmil varchar, valdreauino varchar, datvaldreauino Date, valsigino varchar, datvalsigino Date, valcentralino varchar, datvalcentralino Date)");
            
      $this->db->query("DROP TABLE IF EXISTS w_progproj CASCADE");
      $this->db->query("CREATE TABLE w_progproj AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM progproj_vue') AS t( idptf Integer, idtypact Integer, iddom Integer, representantptf varchar, gdbailfondptf varchar, bailfondptf varchar, agexecptf varchar, progprojptf varchar, autresptf varchar, firmeptf varchar, designationptf varchar, adresseptf varchar, mailptf varchar, telephoneptf varchar, faxptf varchar, sitewebptf varchar, bpptf varchar, persressptf varchar, mailprptf varchar, telprptf varchar, zoneptf varchar, budgettotalptf Integer, validation varchar)");
            
      $this->db->query("DROP TABLE IF EXISTS w_vidangboue CASCADE");
      $this->db->query("CREATE TABLE w_vidangboue AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM vidangboue_vue') AS t(idbou Integer, nibou varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, moymecabou varchar, moymanubou varchar, nbmngaccvidangbou Integer, nblatpubbsvidangbou Integer, volbouvidangbou real, idsittbou Integer, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, nomsittbou varchar, voltraitsittbou real, formelbou varchar, deversementctrlbou varchar, longsittbou real, latsittbou real, altsittbou Integer, valdreaubou varchar, datvaldreaubou Date, valsigbou varchar, datvalsigbou Date, valcentralbou varchar, datvalcentralbou Date, datecollbou Date, datecolldebbou Date, idactbou Integer)");
            
      $this->db->query("DROP TABLE IF EXISTS w_vidangbouetot CASCADE");
                $this->db->query("CREATE TABLE w_vidangbouetot AS SELECT * FROM dblink(' dbname=dbseam user=postgres password=vony', 'SELECT * FROM vidangbouetot_vue') AS t(idbou Integer, nibou varchar, idcom Integer, designationcom varchar, popurbcom Integer, poptotcom Integer, iddis Integer, designationdis varchar, idreg Integer, designationreg varchar, idprov Integer, designationprov varchar, moymecabou varchar, moymanubou varchar, nbmngaccvidangbou Integer, nblatpubbsvidangbou Integer, volbouvidangbou real, idsittbou Integer, idloc Integer, designationloc varchar, idfok Integer, designationfok varchar, nomsittbou varchar, voltraitsittbou real, formelbou varchar, deversementctrlbou varchar, longsittbou real, latsittbou real, altsittbou Integer, valdreaubou varchar, datvaldreaubou Date, valsigbou varchar, datvalsigbou Date, valcentralbou varchar, datvalcentralbou Date, datecollbou Date, datecolldebbou Date, idactbou Integer, idact Integer, designationact varchar, idtypact Integer, designationtypact varchar, idtyptrav Integer, designationtyptrav varchar, idappr Integer, designationappr varchar, idprogproj Integer, progproj varchar, montanttotalact Integer, dureeact real, datreceptprovact Date, observationact varchar, idbail Integer, bailleur varchar, idpart Integer, partmiseoeuvre varchar)");
            
                $this->db->query("DROP TABLE IF EXISTS commune CASCADE");
                $this->db->query("CREATE TABLE commune AS SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 'SELECT * FROM commune') AS t(idcom integer, idmil Integer, designationcom varchar, longcom real, latcom real, altcom Integer, poptotcom Integer, pluviototannuelcom real, nbmenage Integer, iddis Integer, cheflieucom varchar, popurbcom Integer)");
            
                $this->db->query("DROP TABLE IF EXISTS district CASCADE");
                $this->db->query("CREATE TABLE district AS SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 'SELECT * FROM district') AS t(iddis integer, designationdis varchar, longdis real, latdis real, altdis Integer, prioritedis Integer, derniernipo varchar, derniernilaf varchar, dernierninfa varchar, derniernibou varchar, derniernidso varchar, derniernieuep varchar, derniernihyg varchar, idreg Integer, cheflieudis varchar)");
            
                $this->db->query("DROP TABLE IF EXISTS fokontany CASCADE");
                $this->db->query("CREATE TABLE fokontany AS SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 'SELECT * FROM fokontany') AS t(idfok integer, idcom integer, idptf    integer, designationfok    varchar, longfok real, latfok real, altfok real, popfok    real, prioritetecheaufok integer, prioritetechassfok integer, prioriteeaufok integer, prioriteassfok integer,validationfok boolean,    cheflieufok    varchar    , nbmenagefok Integer)");
            
                $this->db->query("DROP TABLE IF EXISTS localites CASCADE");
                $this->db->query("CREATE TABLE localites AS SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 'SELECT * FROM localites') AS t(idloc integer, idfok integer, designationloc varchar, longloc real, latloc real, altloc    real, poploc real, prioritetecheauloc integer, prioritetechassloc integer, nbmenageloc integer, prioriteeauloc    integer, prioriteassloc    integer)");
            
                $this->db->query("DROP TABLE IF EXISTS region CASCADE");
                $this->db->query("CREATE TABLE region AS SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 'SELECT * FROM region') AS t(idreg integer, idprov Integer, designationreg varchar, cheflieureg varchar, longclreg real, latclreg real, altclreg Integer, prioritereg Integer, txaccroispopreg real, txinflationreg real)");
            
                $this->db->query("SELECT AddGeometryColumn ('r010105_localites', 'the_geom',4326, 'POINT',2)");
                $this->db->query("UPDATE r010105_localites SET the_geom = st_setSRID(st_MakePoint(longloc,latloc),4326)");
                $this->db->query("SELECT AddGeometryColumn ('w_dechsolid_vue', 'the_geom',4326, 'POINT',2)");
                $this->db->query("UPDATE w_dechsolid_vue SET the_geom = st_setSRID(st_MakePoint(longsitdec,latsitdec),4326)");
                $this->db->query("SELECT AddGeometryColumn ('w_infraeau', 'the_geom',4326, 'POINT',2)");
                $this->db->query("UPDATE w_infraeau SET the_geom = st_setSRID(st_MakePoint(longino,latino),4326)");
                $this->db->query("SELECT AddGeometryColumn ('w_pointdeau', 'the_geom',4326, 'POINT',2)");
                $this->db->query("UPDATE w_pointdeau SET the_geom = st_setSRID(st_MakePoint(longpdo,latpdo),4326)");
            
?>
