CREATE TABLE w_etablissement  AS 
SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 
'SELECT * FROM etablissement_vue ')
AS t(idets Integer,
idfok Integer,
designationfok varchar,
idcom Integer,
designationcom varchar,
iddis Integer,
designationdis varchar,
idreg Integer,
designationreg varchar,
idclassets Integer,
designationclassets varchar,
idcatets Integer,
designationcatets varchar,
nomets varchar,
amiewashets varchar,
beneficiaireets Integer,
existlatets boolean,
existpdoets boolean,
longets real,
latets real,
altets Integer,
obsets varchar,
typepdoets Integer,
etatouvrets Integer,
typeets varchar)