CREATE TABLE w_hygieneclts AS 
SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 
'SELECT * FROM hygieneclts_vue')
AS t(idhyg Integer,
nihyg varchar,
niveau varchar,
idprov Integer,
designationprov varchar,
idreg Integer,
designationreg varchar,
iddis Integer,
designationdis varchar,
idcom Integer,
designationcom varchar,
popurbcom Integer,
poptotcom Integer,
idfok Integer,
designationfok varchar,
idloc Integer,
designationloc varchar,
poploc Integer,
nbmenageloc Integer,
nbdlmmnghyg Integer,
nbdlmutimnghyg Integer,
nbutilisdlmmnghyg Integer,
datecollhyg Date,
idacclts Integer,
intituleacclts varchar,
dateclts Date,
idacthyg Integer
)
