CREATE TABLE w_infraass AS 
SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 
'SELECT * FROM infraass_vue')
AS t(
idlatinf Integer,
niia varchar,
idtyplat Integer,
designationtyplat varchar,
idloc Integer,
designationloc varchar,
idfok Integer,
designationfok varchar,
idcom Integer,
designationcom varchar,
popurbcom Integer,
poptotcom Integer,
iddis Integer,
designationdis varchar,
idreg Integer,
designationreg varchar,
idprov Integer,
designationprov varchar,
idutil Integer,
designationutil varchar,
idmodgest Integer,
designationmodgest varchar,
nbbenelatinf Integer,
accpershandilatinf varchar,
latinstsepareelatinf varchar,
nbcompatlatinf Integer,
nbdlmlatinf Integer,
nbdouchelatinf Integer,
valdreaulatinf varchar,
datvaldreaulatinf Date,
valsiglatinf varchar,
datvalsiglatinf Date,
valcentrallatinf varchar,
datvalcentrallatinf Date,
observations varchar,
idactlatinf Integer
)