CREATE TABLE w_pointdeautot  AS 
SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 
'SELECT * FROM pointdeautot_vue')
AS t(idpdo Integer,
idtyppdo Integer,
designationtyppdo varchar,
designation2typpdo varchar,
idutil Integer,
designationutil varchar,
idloc Integer,
designationloc varchar,
poploc Integer,
idfok Integer,
designationfok varchar,
idcom Integer,
designationcom varchar,
popurbcom Integer,
poptotcom Integer,
iddis Integer,
designationdis varchar,
idreg Integer,
designationreg varchar,
idprov Integer,
designationprov varchar,
idmodgest Integer,
designationmodgest varchar,
idfoncouvr Integer,
desigfoncouvr varchar,
idino Integer,
numpdo Integer,
gerantpdo varchar,
nbbenepdo Integer,
popdesspdo Integer,
longpdo real,
latpdo real,
altpdo Integer,
idtypineau Integer,
designationtypineau varchar,
nbpdo Integer,
idmil Integer,
designationmil varchar,
idets Integer,
idact Integer,
idtyptrav Integer,
designationtyptrav varchar,
datreceptprovact Date
)
