CREATE TABLE w_vidangboue  AS 
SELECT * FROM dblink('dbname=dbseam user=postgres password=vony', 
'SELECT * FROM vidangboue_vue')
AS t(
idbou Integer,
nibou varchar,
idcom Integer,
designationcom varchar,
popurbcom Integer,
poptotcom Integer,
iddis Integer,
designationdis varchar,
idreg Integer,
designationreg varchar,
idprov Integer,
designationprov varchar,
moymecabou varchar,
moymanubou varchar,
nbmngaccvidangbou Integer,
nblatpubbsvidangbou Integer,
volbouvidangbou real,
idsittbou Integer,
idloc Integer,
designationloc varchar,
idfok Integer,
designationfok varchar,
nomsittbou varchar,
voltraitsittbou real,
formelbou varchar,
deversementctrlbou varchar,
longsittbou real,
latsittbou real,
altsittbou Integer,
valdreaubou varchar,
datvaldreaubou Date,
valsigbou varchar,
datvalsigbou Date,
valcentralbou varchar,
datvalcentralbou Date,
datecollbou Date,
datecolldebbou Date,
idactbou Integer
)
